// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKG-TZe1wlGIy-IylZgxU6C_WZyuSwrkY',
    appId: '1:382372436134:web:6254a528905f1ce6ccfc67',
    messagingSenderId: '382372436134',
    projectId: 'fishpond-b08fa',
    authDomain: 'fishpond-b08fa.firebaseapp.com',
    storageBucket: 'fishpond-b08fa.firebasestorage.app',
    measurementId: 'G-CE1FG00CJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkfcSG43DUQg-jQHHVMBHFIF4fxsnnxLo',
    appId: '1:382372436134:android:ed043c251ca3f789ccfc67',
    messagingSenderId: '382372436134',
    projectId: 'fishpond-b08fa',
    storageBucket: 'fishpond-b08fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0qBp7IM4b23h-4DwIg83ZjodiH3aap5s',
    appId: '1:382372436134:ios:e5927122897d42d2ccfc67',
    messagingSenderId: '382372436134',
    projectId: 'fishpond-b08fa',
    storageBucket: 'fishpond-b08fa.firebasestorage.app',
    iosBundleId: 'com.example.fishpond',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0qBp7IM4b23h-4DwIg83ZjodiH3aap5s',
    appId: '1:382372436134:ios:e5927122897d42d2ccfc67',
    messagingSenderId: '382372436134',
    projectId: 'fishpond-b08fa',
    storageBucket: 'fishpond-b08fa.firebasestorage.app',
    iosBundleId: 'com.example.fishpond',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKG-TZe1wlGIy-IylZgxU6C_WZyuSwrkY',
    appId: '1:382372436134:web:cb6f16cdcec5a386ccfc67',
    messagingSenderId: '382372436134',
    projectId: 'fishpond-b08fa',
    authDomain: 'fishpond-b08fa.firebaseapp.com',
    storageBucket: 'fishpond-b08fa.firebasestorage.app',
    measurementId: 'G-XR89Q7189Z',
  );
}
